Feature/account activate
lan1dev/lan-event-platform pull request #48
Opened 2018-07-05 20:31 UTC by JSudden

2018-07-05 20:32 UTC, JSudden commented
Issue26 Glömde lägga in Close #26 i commit

2018-07-05 21:22 UTC, Wiktorsson approved these changes
Fint

2018-07-06 00:43 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> + * DashboardPage for the /dashboard route
Kommentar stämmer inte

2018-07-06 00:44 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +import DashboardBase from './DashboardBase';
DashboardBase används inte någonstans.

2018-07-06 00:44 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +        <Button>Create Ticket</Button>
Fel text

2018-07-06 00:45 UTC, JohanG2012 commented on client/views/routes/index.jsx
> +    <Route path="/activate" component={ActivatePage} />
Borde kanske vara "activated" eller till och med "user/activated"

2018-07-06 00:46 UTC, JohanG2012 requested changes
Fixa kommentarerna, annars ser det bra ut =) 

Gällande att du glömde stänga via commit, så kan du köra `git commit --amend` för att editer din senaste commit. Eller stänge när du fixat ovanstående :)

2018-07-06 00:50 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +    <Modal background="lightgray">
En modal behövs nog troligtvis inte här.

2018-07-06 00:57 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +const ActivatePage = () => (
Appen Krashar.
![image](https://user-images.githubusercontent.com/9220635/42354580-1808fafc-80c8-11e8-895d-c3a0126c64b8.png)

Se: 
https://reactjs.org/docs/fragments.html
https://stackoverflow.com/questions/31284169/parse-error-adjacent-jsx-elements-must-be-wrapped-in-an-enclosing-tag
https://github.com/lan1dev/Playground-React-Redux/blob/master/src/views/components/ToDoApp.jsx

2018-07-06 01:02 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +import DashboardBase from './DashboardBase';
Konstigt att det inte gav ESlint fel under pre-commit hook...

2018-07-06 07:36 UTC, JohanG2012 commented
Skapa även ett issue att tester saknas för komponenten :)

2018-07-06 07:42 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> +    <Modal background="lightgray">
Jag tror även vi har Engelska på övriga views? Kör det här med så vi är konsekventa :)

2018-07-06 07:43 UTC, JohanG2012 commented on client/views/routes/index.jsx
> +    <Route path="/activate" component={ActivatePage} />
Även komponenten bör nog heta "ActivatedPage" eller "AccountActivatedPage"

2018-07-06 19:24 UTC, JohanG2012 requested changes

2018-07-06 19:24 UTC, JohanG2012 commented on client/views/pages/AccountActivate.jsx
> - * DashboardPage for the /dashboard route
Routen är inte dashboard den är "/user/activated"

2018-07-06 19:24 UTC, JohanG2012 commented on client/views/routes/index.jsx
> +import AccountActivatedPage from '../pages/AccountActivate';
Filen bör ha samma namn som komponenten

2018-07-06 22:15 UTC, JohanG2012 approved these changes

2018-07-06 22:17 UTC, merged